
# æ ¹æ® schema æä¾›è‡ªåŠ¨è¡¥å…¨
"$schema" = 'https://starship.rs/config-schema.json'

# åœ¨æç¤ºç¬¦ä¹‹é—´æ’å…¥ç©ºè¡Œ
add_newline = true

[directory]
home_symbol = 'ğŸ‘½~'

[git_status]
modified = 'â‡£${count}'
staged = '+${count}'

[character]
success_symbol = '[âœ”](bold green) '
error_symbol = '[âœ—](bold red) '

[memory_usage]
disabled = false
threshold = -1
format = '$symbol [${ram_pct}]($style)  '
symbol = 'ğŸš€'


